% restoredefaultpath;
folder = mfilename('fullpath');
cwd = fileparts(folder);
addpath(genpath([cwd, filesep]));

set(groot, 'DefaultLineLineWidth', 2, ...
           'DefaultTextInterpreter', 'LaTeX', ...
           'DefaultAxesTickLabelInterpreter', 'LaTeX', ...
           'DefaultAxesFontName', 'LaTeX', ...
           'DefaultTextFontName', 'LaTeX', ...
           'DefaultLegendInterpreter', 'LaTeX', ...
           'DefaultColorbarTicklabelInterpreter', 'LaTeX', ...
           'DefaultAxesLineWidth', 1.5, ...
           'DefaultAxesFontSize', 16, ...
           'DefaultAxesFontSizeMode', 'Manual', ...
           'defaultAxesLabelFontSizeMultiplier', 1, ...
           'defaultAxesTitleFontSizeMultiplier', 1, ...
           'DefaultLegendFontSize', 16, ...
           'DefaultLegendFontSizeMode', 'Manual', ...
           'DefaultLegendColor', [1 1 1], ...
           'DefaultLegendBox', 'on', ...
           'DefaultColorbarFontSize', 16, ...
           'DefaultColorbarFontSizeMode', 'Manual', ...
           'DefaultTextFontSize', 16, ...
           'DefaultTextFontSizeMode', 'Manual', ...
           'DefaultAxesBox', 'on', ...
           'DefaultAxesNextPlot', 'replace', ...
           'DefaultAxesXGrid', 'on', ...
           'DefaultAxesYGrid', 'on', ...
           'DefaultAxesZGrid', 'on', ...
           'DefaultAxesColor', [1, 1, 1], ...
           'DefaultFigureColor', [1, 1, 1], ...
           'DefaultFigureInvertHardcopy', 'off' ...
           );
set(groot, 'DefaultFigureUnits', 'inches', ...
           'DefaultFigurePaperPosition', [0, 0, 8, 6], ...
           'DefaultFigurePaperSize', [8.5, 6.5], ...
           'DefaultFigurePosition', [0, 0, 8, 6]);    
disp(['Welcome to saga-utils. The current working folder is', cwd]);
format short g;
