function fig_handle = pltatm(auto_mode)

% Example function to plot simulated atmospheric effects on PR measurements
% The simulated data are loaded from the file demoplt1.mat
% which is generated by the example function demoplt1.m
% Input:
%   auto_mode = optional flag (only include when in auto mode)

% Written by: Jimmy LaMance 9/5/97
% Copyright (c) 1998 by Constell, Inc.

% load in the data
load demoplt1

if nargin < 1,
  % Get the screen size in pixels to use for location of plots
  set(0,'units','pixels');
  screen_size = get(0,'screensize');
  y_max = screen_size(2) + screen_size(4) - 60;
  x_max = screen_size(1) + screen_size(3) - 50;
  x_step = 110;
  y_step = 60 + y_max;

  % set the figure colors to be black background like Matlab 4
  colordef none                                

  % generate the position error figure
  fig_handle = figure('color','black', ...
     'position',[30 50 x_max-30 y_max-50],  ...
     'NumberTitle','off', ...
     'Name','Atmospheric Delays', ...
     'Tag','fign');
end;

fig_title_cell={'Atmospheric Path Delay Modeling';};
x = t_pr_base;
y = total_tropb;
prn = prn_base;
axis_label_cell = {''; 'Troposphere Delay (m)';char(fig_title_cell);};

legend_cell = {''};

descriptive_text_cell = ...
 {'The Constellation Toolbox provides the ability to model atmospheric path delays'; ...
  'caused by the troposphere and ionosphere.  Unmodeled, these delays or biases';
  'can lead to over 100 meters of error on the pseudorange measurement leading to';
  'large position errors.  For the differential user, residual troposphere and';
  'ionosphere delays are some the largest error sources, particulurly for low';
  'elevation satellites.  Troposphere delays with 10 deg mask are shown below.'};

if nargin < 1,
  textwin2(fig_title_cell,x,y,prn,axis_label_cell,legend_cell, ...
      descriptive_text_cell,1);

  % Determine the location for the plot in upper right corner
  x_min = x_max / 10;
  y_min = y_max / 10;

  % set the figure position
  set(fig_handle,'position',[x_min y_min x_max/1.25 y_max/1.25]);
else,
  fig_handle = gcf;
  textwin2(fig_title_cell,x,y,prn,axis_label_cell,legend_cell, ...
      descriptive_text_cell);
end;

% end of PLTATM
