function fig_handle = pltnav(auto_mode)

% Example function to plot processed simulated PR measurements with S/A
% The data are loaded from the file demoplt1.mat
% which is generated by the example function demoplt1.m
% Input:
%   auto_mode = optional flag (only include when in auto mode)

% Written by: Jimmy LaMance 9/5/97
% Copyright (c) 1998 by Constell, Inc.

% load in the data
load demoplt1

% compute the total position error and add it to the NED position error matrix
[unit_err, total_pos_err] = normvect(pos_err_ned);

pos_err_ned = [pos_err_ned total_pos_err];

if nargin < 1,
  % Get the screen size in pixels to use for location of plots
  set(0,'units','pixels');
  screen_size = get(0,'screensize');
  y_max = screen_size(2) + screen_size(4) - 60;
  x_max = screen_size(1) + screen_size(3) - 50;
  x_step = 110;
  y_step = 60 + y_max;

  % set the figure colors to be black background like Matlab 4
  colordef none                                

  % generate the position error figure
  fig_handle = figure('color','black', ...
   'position',[30 50 x_max-30 y_max-50],  ...
   'NumberTitle','off', ...
   'Name','Simulated Position Solution', ...
   'Tag','fign');
end;

fig_title_cell={'Simulated Position Solution';};
x = plot_time ./ 60;
y = pos_err_ned;
axis_label_cell = {'Minutes Since Start'; 'Position Error (m)'; ...
  'Position Errors Caused by SA, Atmospheric Delays, and Receiver Noise';};

legend_cell = {'North','East','Down','Total'};

descriptive_text_cell = ...
 {'Simulating position errors from GPS receivers is more that just adding white';
  'noise.  The effects of Selective Availability (SA), atmospheric path delays, ';
  'and receiver noise all play a role in the position error.  These errors all';
  'effect the pseudorange and Doppler measurements directly and are incorporated';
  'into the position solution as a function of the satellite geometry.  The Constellation ';
  'Toolbox allows the user to properly model these effects on the position accuracy.'};

if nargin < 1,
  text_win(fig_title_cell,x,y,axis_label_cell,legend_cell, ...
      descriptive_text_cell,1);

  % Determine the location for the plot in upper right corner
  x_min = x_max / 10;
  y_min = y_max / 10;

  % set the figure position
  set(fig_handle,'position',[x_min y_min x_max/1.25 y_max/1.25]);
else,
  fig_handle = gcf;
  text_win(fig_title_cell,x,y,axis_label_cell,legend_cell, ...
      descriptive_text_cell);
end;

% end of PLTNAV
