function fig_handle = pltnmsa(auto_mode)

% Example function to plot PSD of the position data obtained from NMEA data.
% The data are loaded from the file demonmea.mat
% which is generated by the example function ex_nmea with a subset of the
% data saved for the demo.
% Input:
%   auto_mode = optional flag (only include when in auto mode)

% Written by: Jimmy LaMance 9/6/97
% Copyright (c) 1998 by Constell, Inc.

% load in the data
load demonmea;

if nargin < 1,
  % Get the screen size in pixels to use for location of plots
  set(0,'units','pixels');
  screen_size = get(0,'screensize');
  y_max = screen_size(2) + screen_size(4) - 60;
  x_max = screen_size(1) + screen_size(3) - 50;
  x_step = 110;
  y_step = 60 + y_max;

  % set the figure colors to be black background like Matlab 4
  colordef none;                               

  % Determine the location for the plot in upper right corner
  x_min = x_max / 10;
  y_min = y_max / 10;

  % generate the position error figure
  fig_handle = figure('color','black', ...
   'position',[x_min y_min x_max/1.25 y_max/1.25],  ...
   'NumberTitle','off', ...
   'Name','NMEA Data: Position Power Spectral Densities', ...
   'Tag','fign');
end;

fig_title_cell={'Position PSD';};
x = period;
y = Pyy(1:num_freqs,:);
axis_label_cell = {'Period (minutes)'; 'Power'; ...
  'North, East, Down Position Power Spectral Densities Using NMEA Data';};

legend_cell = {'North','East','Down'};

descriptive_text_cell = ...
 {'When the data analysis is more complex than means and standard deviations,';
  'Matlab and the Constellation Toolbox rise to the occasion.  Shown here is a Power ';
  'Spectral Density (PSD) plot of the position variations in NED coordinates.';
  'This analysis provides insight into the true nature of the Selective ';
  'Availability (SA) characteristics.  Note the power in the longer periods.  This';
  'data was collected using ProComm and a Garmin 12XL receiver on July 4, 1997.'};

if nargin < 1,
  text_win(fig_title_cell,x,y,axis_label_cell,legend_cell, ...
      descriptive_text_cell,1);
else, 
  fig_handle = gcf;
  text_win(fig_title_cell,x,y,axis_label_cell,legend_cell, ...
      descriptive_text_cell);
end;

% set the axis to show the number of satellites (add +/-1 to the y-axis)
% vs = axis;
% axis([vs(1) vs(2) vs(3)-1 vs(4)+1]);

% end of PLTNMSA
