function fig_handle = pltsimpr

% Example function to plot simulated PR measurements
% The simulated PR measurements are loaded from the file ex_dpgs.mat
% which is generated by the example function ex_dpgs.m

% Written by: Jimmy LaMance 9/5/97
% Copyright (c) 1998 by Constell, Inc.

% load in the data
load ex_dpgs

% generate the position error figure
figure
subplot(2,1,1)
plot(plot_time,pos_err_ned)
legend('North','East','Down',-1);
ylabel('Position Err (m)')                
title_string = ...
  sprintf('Position Errors without DGPS with a %d km Baseline',...
           round(base_line_km));
title(title_string) 

subplot(2,1,2)
plot(pos_err_ned_dgps)
legend('North','East','Down',-1);
ylabel('Position Err (m)')
title_string = ...
  sprintf('Position Errors with DGPS with a %d km Baseline',...
           round(base_line_km));
title(title_string) 
xlabel('time past start (sec)') 

% compute the total SA error contribution to the PR measurement
pr_sa_err = sa_eps_err + sa_clk_err;

% generate the plots for S/A errors
plot_svn(t_pr_base,pr_sa_err,prn_base,'SA PR err (m)',...
         'Example of SA Errors on Pesudo-range Measurements');
         
% plot troposphere contribution to the PR error
total_trop = trop_wet + trop_dry;
plot_svn(t_pr_base,total_trop,prn_base,'Tropo (m)',...
         'Example of Troposphere Effects Pesudo-range Measurements');

% plot the receiver clock bias for a single satellite 
% the receiver clock bias is common to all satellites
I = find(prn_base == prn_base(1));
plot_svn(t_pr_base(I,:),clk_bias(I),prn_base(I),'Clock Bias (m)',...
         'Example of Receiver Clock Bias Pesudo-range Measurements');

plot_svn(t_pr_base(I,:),clk_drift(I),prn_base(I),'Clock Drift (m/2)',...
         'Example of Receiver Clock Drift Pesudo-range Measurements');

if save_plot_data == 1
  % save the data to a mat file for regeneration later
  save ex_dpgs plot_time pos_err_ned pos_err_ned_dgps ...
       t_pr_base pr_sa_err clk_bias clk_drift total_trop prn_base
end % if save_plot_data == 1

         